name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

env:
  REGISTRY: docker.io/stjepanr
  IMAGE_NAME: crypto-bot
  REPOSITORY_NAME: crypto-bot
  GITHUB_USERNAME: StjepanR

jobs:
  test:
    name: Test with Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test the Docker image
        run: |
          pip install -r requirements.txt
          pytest -v ./test/
  push_to_registry:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.MAJOR }}.${{ secrets.MINOR }}.${{ secrets.PATCH }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Update patch version
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'PATCH'
          value: $((${{ secrets.PATCH }}+1))
          repository: ${{ env.GITHUB_USERNAME }}/${{ env.REPOSITORY_NAME }}
          token: ${{ secrets.VERSION_UPGRADE_ACCESS_TOKEN }}
