name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ "dev", "master" ]
  pull_request:
    branches: [ "dev", "master" ]

env:
  REGISTRY: docker.io/stjepanr
  IMAGE_NAME: crypto-bot
  REPOSITORY_NAME: crypto-bot
  REPOSITORY_OWNER: StjepanR
  SECRET_NAME: PATCH

jobs:
  test:
    name: Test with Pytest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test the Docker image
        run: |
          pip install -r requirements.txt
          pytest -v ./test/

  update_patch_version:
    name: Update Patch Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set env
        env:
          NEW_SECRET_VALUE: ${{ secrets.PATCH }}
        run: |
          NEW_SECRET_VALUE = $(( NEW_SECRET_VALUE + 1 ))
          echo $NEW_SECRET_VALUE

      - name: Update Secret
        uses: gliech/create-github-secret-action@v1
        with:
          location: ${{ env.REPOSITORY_OWNER }}/${{ env.REPOSITORY_NAME }}
          name: ${{ env.SECRET_NAME }}
          value:  ${{ env.NEW_SECRET_VALUE }}
          pa_token: ${{ secrets.VERSION_UPGRADE_ACCESS_TOKEN }}

  push_to_registry:
    name: Build and Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REPOSITORY_OWNER }}/${{ env.IMAGE_NAME }}:${{ secrets.MAJOR }}.${{ secrets.MINOR }}.${{ secrets.PATCH }}